blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/Pappet/harux/discussions
    about: Ask questions or start a discussion (not a bug or feature request)
